
[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "buttonless"

# opacity = 0.5
opacity = 0.825
blur = true

option_as_alt = "OnlyLeft"

[font]
# normal = { family = "JetBrainsMono Nerd Font", style = "Medium" }
normal = { family = "BlexMono Nerd Font Propo", style = "Medium" }

size = 16

[general]
import = ["~/.config/alacritty/themes/night_owl.toml"]
