import = ["~/.config/alacritty/themes/night_owl.toml"]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "buttonless"

opacity = 0.5
blur = true

[font]
normal.family = "MesloLGS Nerd Font Mono"

size = 17
